/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-03-24 12:10:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.logon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inputForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/logon/color.jsp", Long.valueOf(1458819778452L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

String bodyback_c="#e0ffff";
String back_c="#8fbc8f";
String title_c="#5f9ea0";
String value_c="#b0e0e6";
String bar="#778899";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title> 회원가입 </title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\tfunction chekIt(){\r\n");
      out.write("\t\tvar userinput = eval(\"document.userinput\");\r\n");
      out.write("\t\tif(!userinput.id.value){\r\n");
      out.write("\t\t\talert(\"ID 를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!userinput.passwd.value){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!userinput.name.value){\r\n");
      out.write("\t\t\talert(\"사용자의 이름을 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!userinput.jumin1.value || !userinput.jumin2.value){\r\n");
      out.write("\t\t\talert(\"주민등록번호를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t//아이디 중복 여부를 판단\r\n");
      out.write("\tfunction openConfirmid(userinput){\r\n");
      out.write("\t\t//아이디를 입력해는지 검사\r\n");
      out.write("\t\tif(userinput.id.value == \"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//url과 사용자 입력 id 를 조합합니다.\r\n");
      out.write("\t\turl= \"confirmId.jsp?id=\"+userinput.id.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//새로운 윈도우를 엽니다.\r\n");
      out.write("\t\topen(url,\"confirm\", \"toolbar=no, location = no, status =no, menubar=no, scrollbars=no, resizable=no,width=300,height=200\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction zipCheck(){\r\n");
      out.write("\t\turl=\"ZipCheck.jsp?check=y\";\r\n");
      out.write("    \t\r\n");
      out.write("    \twindow.open(url,\"post\",\"toolbar=no ,width=500 ,height=300,directories=no,status=yes,scrollbars=yes,menubar=no\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor = \"");
      out.print(bodyback_c);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"inputPro.jsp\" name = \"userinput\" onSubmit=\"return checkIt()\">\r\n");
      out.write("\t<table width=\"600\" border = \"1\" cellspacing=\"0\" cellpadding =\"3\" align=\"center\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan =\"2\" height = \"39\" align = \"center\" bgcolor= \"");
      out.print( value_c );
      out.write("\">\r\n");
      out.write("\t\t\t\t<font size= \"+1\"><b>회원가입</b></font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr> \r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"200\" bgcolor = \"");
      out.print(value_c);
      out.write("\"> <b>아이디 입력</b></td>\r\n");
      out.write("\t\t\t<td width =\"400\" bgcolor = \"");
      out.print(value_c);
      out.write("\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width = \"200\"> 사용자 ID</td>\r\n");
      out.write("\t\t\t<td width = \"400\"> \r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"id\" size=\"10\" maxlength=\"12\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" name = confirm_id\" value=\"ID중복확인\" Onclick =\"openConfirmid(this.form)\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"200\"> 비밀번호</td>\r\n");
      out.write("\t\t\t<td width=\"400\">\r\n");
      out.write("\t\t\t\t<input type=\"password\" name= \"passwd\" size=\"15\" maxlength=\"12\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width = \"200\" bgcolor=\"");
      out.print(value_c );
      out.write("\"><b>개인정보 입력</b></td>\r\n");
      out.write("\t\t\t<td width = \"400\" bgcolor=\"");
      out.print(value_c );
      out.write("\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width =\"200\"> 사용자 이름</td>\r\n");
      out.write("\t\t\t<td width=\"400\" > \r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"name\" size=\"15\" maxlength=\"10\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("      <td width=\"200\">주민등록번호</td>\r\n");
      out.write("      <td width=\"400\">\r\n");
      out.write("        <input type=\"text\" name=\"jumin1\" size=\"7\" maxlength=\"6\">\r\n");
      out.write("        -<input type=\"text\" name=\"jumin2\" size=\"7\" maxlength=\"7\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td width=\"200\">E-Mail</td>\r\n");
      out.write("      <td width=\"400\">\r\n");
      out.write("        <input type=\"text\" name=\"email\" size=\"40\" maxlength=\"30\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td width=\"200\"> Blog</td>\r\n");
      out.write("      <td width=\"400\">\r\n");
      out.write("        <input type=\"text\" name=\"blog\" size=\"60\" maxlength=\"50\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("       <td width=\"200\">우편번호</td>\r\n");
      out.write("       <td> <input type=\"text\" name=\"zipcode\" size=\"7\" readonly>\r\n");
      out.write("               <input type=\"button\" value=\"우편번호찾기\" onClick=\"zipCheck()\">\r\n");
      out.write("               우편번호를 검색하세요.</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    <tr> \r\n");
      out.write("       <td>주소</td>\r\n");
      out.write("       <td><input type=\"text\" name=\"address\" size=\"70\">\r\n");
      out.write("       주소를 적어 주세요.</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td colspan=\"2\" align=\"center\" bgcolor=\"");
      out.print(value_c);
      out.write("\">\r\n");
      out.write("          <input type=\"submit\" name=\"confirm\" value=\"등   록\" >\r\n");
      out.write("          <input type=\"reset\" name=\"reset\" value=\"다시입력\">\r\n");
      out.write("          <input type=\"button\" value=\"가입안함\" onclick=\"javascript:window.location='main.jsp'\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
